---
- name: Make user for EzyAdmin connection
  hosts: all
  tasks:
    - name: "Install: packages using a list"
      become: true
      when: ansible_os_family == "RedHat"
      yum:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - perl
          - perl-Data-Dumper

    - name: "Install: packages using a list"
      become: true
      when: ansible_distribution in ['Ubuntu', 'Debian']
      apt:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - perl

    - name: Copy script make user for authentication
      become: true
      template: 
        src: ezy_authentication.pl.j2
        dest: /ezy_authentication.pl
        owner: root
        group: root
        mode: 0700

    - name: Run script make user for authentication
      become: true
      command: /usr/bin/perl /ezy_authentication.pl

    - name: Read activate EzyAdmin data file
      become: true
      command: cat /etc/ezyadmin_activate.data
      register: ezyadmin_activate

    - name: Display EzyAdmin activate data
      debug:
        msg: "{{ezyadmin_activate.stdout}}"